<Project>
  <PropertyGroup>
    <Version>0.2.3</Version>
    <Authors>tojollinor</Authors>
    <Company>tojollinor</Company>
    <Product>SimplePrint</Product>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
</Project>